-- Drop existing tables if they exist
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Class_Enrollment CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Class CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Member CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Trainer CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Membership_Plan CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE App_User CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL; -- Skip if table doesn't exist
END;
/

-- 1. Member Table
CREATE TABLE Member (
    MemberID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name            VARCHAR2(100),
    ContactInfo     VARCHAR2(100),
    MembershipType  VARCHAR2(20), -- 'Basic' or 'Premium'
    JoinDate        DATE
);

-- 2. Trainer Table
CREATE TABLE Trainer (
    TrainerID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name            VARCHAR2(100),
    Specialization  VARCHAR2(100)
);

-- 3. Membership_Plan Table
CREATE TABLE Membership_Plan (
    PlanID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Type            VARCHAR2(20), -- 'Basic' or 'Premium'
    Duration        NUMBER,       -- In months
    Cost            NUMBER(8,2)
);

-- 4. Class Table
CREATE TABLE Class (
    ClassID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name            VARCHAR2(100),
    Schedule        VARCHAR2(100),
    TrainerID       NUMBER,
    MaxEnrollment   NUMBER DEFAULT 10,
    CONSTRAINT fk_trainer FOREIGN KEY (TrainerID) REFERENCES Trainer(TrainerID)
);

-- 5. Class_Enrollment Table
CREATE TABLE Class_Enrollment (
    EnrollmentID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MemberID        NUMBER,
    ClassID         NUMBER,
    CONSTRAINT fk_member FOREIGN KEY (MemberID) REFERENCES Member(MemberID),
    CONSTRAINT fk_class FOREIGN KEY (ClassID) REFERENCES Class(ClassID),
    CONSTRAINT uq_member_class UNIQUE (MemberID, ClassID)
);

-- 6. User Table (for Admin/Trainer login)
CREATE TABLE User (
    UserID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username        VARCHAR2(100) UNIQUE NOT NULL,
    PasswordHash    VARCHAR2(255) NOT NULL,
    Role            VARCHAR2(20) CHECK (Role IN ('admin', 'trainer'))
);
